version: "3.8"

services:
  postgres:
    container_name: next-movies
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nextMovies
      POSTGRES_DB: nextMovies

volumes:
  postgres_data:
